# Generated by Django 5.1.7 on 2025-04-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersecurityprofile",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
